fix mononoke build error on megarepo error backtrace
mononoke uses anyhow's backtrace feature.  anyhow 1.0.74 changed its build.rs detection for backtrace which no longer finds it in the the "stable compiler plus RUSTC_BOOTSTRAP set" combination

For now fix cargo by pinning the Cargo build to the existing 1.0.71 requirement.

Test plan:

Build locally on macOS with `./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. mononoke`

Before, fails:
    ```
    error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
      --> megarepo_api/megarepo_error/src/lib.rs:33:24
       |
    33 |                 self.0.backtrace()
       |                        ^^^^^^^^^ method not found in `Arc<Error>`
    ...
    61 | cloneable_error!(InternalError);
       | ------------------------------- in this macro invocation
    ```

After, works