fix ubuntu 22.04 gcc 11.3 incompatibility in ImmediateFuture.h
Build breaks on ubuntu 22.04, fix it.  There was a GCC incompability in ImmediateFuture.h, enum needed to be public to make it build.

Test plan:

Run locally: `./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. eden`

Before:
```
FAILED: eden/fs/utils/CMakeFiles/eden_utils.dir/ImmediateFuture.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DFOLLY_XLOG_STRIP_PREFIXES=\"/home/alex/local/sapling:/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/build/eden\" -DGFLAGS_IS_A_DLL=0 -I/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/build/eden -I/home/alex/local/sapling -I/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/blake3-pvW45K3j2Cg4SJhyw_BLKOgg_GF5YOibrzfrXqKH26E/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/folly/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fb303/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fizz/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/wangle/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fbthrift/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fmt-YT_9fAD55T6NzivmQ4MY1M6PmZqXHrcPjYyqQHf4z-U/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/mvfst/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/edencommon/include -g -Wall -Wextra -Wno-deprecated -Wno-deprecated-declarations -Wno-nullability-completeness -Wno-unknown-pragmas -O2 -g -DNDEBUG -fsized-deallocation -MD -MT eden/fs/utils/CMakeFiles/eden_utils.dir/ImmediateFuture.cpp.o -MF eden/fs/utils/CMakeFiles/eden_utils.dir/ImmediateFuture.cpp.o.d -o eden/fs/utils/CMakeFiles/eden_utils.dir/ImmediateFuture.cpp.o -c /home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp: In function ‘facebook::eden::ImmediateFuture<folly::Unit> facebook::eden::makeNotReadyImmediateFuture()’:
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp:14:72: error: class template argument deduction failed:
   14 |       ImmediateFuture<folly::Unit>::SemiFutureReadiness::LazySemiFuture};
      |                                                                        ^
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp:14:72: error: no matching function for call to ‘ImmediateFuture(folly::SemiFuture<folly::Unit>, facebook::eden::ImmediateFuture<folly::Unit>::SemiFutureReadiness)’
In file included from /home/alex/local/sapling/eden/fs/utils/ImmediateFuture.h:443,
                 from /home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp:8:
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture-inl.h:52:1: note: candidate: ‘template<class T> ImmediateFuture(folly::SemiFuture<T>, typename facebook::eden::ImmediateFuture<T>::SemiFutureReadiness)-> facebook::eden::ImmediateFuture<T>’
   52 | ImmediateFuture<T>::ImmediateFuture(
      | ^~~~~~~~~~~~~~~~~~
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture-inl.h:52:1: note:   template argument deduction/substitution failed:
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture-inl.h: In substitution of ‘template<class T> ImmediateFuture(folly::SemiFuture<T>, typename facebook::eden::ImmediateFuture<T>::SemiFutureReadiness)-> facebook::eden::ImmediateFuture<T> [with T = folly::Unit]’:
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp:14:72:   required from here
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture-inl.h:52:1: error: ‘enum class facebook::eden::ImmediateFuture<folly::Unit>::SemiFutureReadiness’ is private within this context
In file included from /home/alex/local/sapling/eden/fs/utils/ImmediateFuture.cpp:8:
/home/alex/local/sapling/eden/fs/utils/ImmediateFuture.h:295:14: note: declared private here
  295 |   enum class SemiFutureReadiness {

```

After, gets past this to RingBuffer.h problem which is fixed in next in stack