fix mononoke build errors
fix two problems to causing build errors on mononoke macOS build.   For mononoke linux the next change in the stack to fix linking is also needed

1) mononoke uses anyhow's backtrace feature.  anyhow 1.0.74 changed its build.rs detection for backtrace which no longer finds it in the the "stable compiler plus RUSTC_BOOTSTRAP set" combination

For now fix cargo by pinning the Cargo build to the existing 1.0.71 requirement.

2) rust 1.72 removed the hash_drain_filter feature, which causes the build to start to fail.  Removed the usage.

Test plan:

mononoke macOS CI, goes from broken to working

Build locally on macOS with `./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. mononoke`

Before, fails:
    ```
    error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
      --> megarepo_api/megarepo_error/src/lib.rs:33:24
       |
    33 |                 self.0.backtrace()
       |                        ^^^^^^^^^ method not found in `Arc<Error>`
    ...
    61 | cloneable_error!(InternalError);
       | ------------------------------- in this macro invocation
    ```

and on rust 1.72 failed with
```
Command '['cargo', 'build', '--workspace', '-j2', '--out-dir', '/tmp/fbcode_builder_getdeps-ZhomeZrunnerZworkZsaplingZsaplingZbuildZfbcode_builder/installed/mononoke/bin', '-Zunstable-options']' returned non-zero exit status 101.
!! Failed
error[E0635]: unknown feature `hash_drain_filter`
 --> cmdlib/sharding/src/lib.rs:8:12
  |
8 | #![feature(hash_drain_filter)]
  |            ^^^^^^^^^^^^^^^^^
```

After, works