get mononoke green in github CI
Summary:
* mononoke [unit tests are failing](https://github.com/facebook/sapling/actions/runs/11477571042/job/31939940450#step:85:8352),  fix them
* test-cross-repo-mononoke-git-sot.t deleted, remove from exclusion list

Test Plan:

**Local run of unittest**
```
./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. mononoke
./build/fbcode_builder/getdeps.py --allow-system-packages test--src-dir=. mononoke
```

Before fails:
```
failures:
    store::test::test_find_abandoned_requests
    store::test::test_get_stats
    store::test::test_mark_as_new
```

After, passes.

**Local run of integration test**
```
# first build sapling cli & install system deps
./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. sapling
./build/fbcode_builder/getdeps.py install-system-deps --recursive mononoke_integration
# then test mononoke
./build/fbcode_builder/getdeps.py --allow-system-packages build --no-deps --src-dir=. mononoke_integration
./build/fbcode_builder/getdeps.py --allow-system-packages test --src-dir=. mononoke_integration
```

Before, fails
```
AssertionError: The test groups contain not existing tests: ['cross_repo/test-cross-repo-mononoke-git-sot-switch.t'] in /home/runner/work/sapling/sapling/eden/mononoke/tests/integration
```

After, passes:
```
```