fix ubuntu 22.04 missing include in RingBuffer.h
RingBuffer.h was missing the size_t type causing its test to fail to build, so included it

Test plan:

Build locally: `./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. eden`

Before:
```
[365/418] Building CXX object eden/fs/utils/test/CMakeFiles/eden_utils_test.dir/RingBufferTest.cpp.o
FAILED: eden/fs/utils/test/CMakeFiles/eden_utils_test.dir/RingBufferTest.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DFOLLY_XLOG_STRIP_PREFIXES=\"/home/alex/local/sapling:/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/build/eden\" -DGFLAGS_IS_A_DLL=0 -I/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/build/eden -I/home/alex/local/sapling -I/home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/blake3-pvW45K3j2Cg4SJhyw_BLKOgg_GF5YOibrzfrXqKH26E/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/folly/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fb303/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fizz/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/wangle/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fbthrift/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/googletest-yfoodwvrQ1_h8Cxwb6gHyZ2Qt2-vKG3oCpgtoM1DYkQ/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/fmt-YT_9fAD55T6NzivmQ4MY1M6PmZqXHrcPjYyqQHf4z-U/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/mvfst/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/edencommon/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/cpptoml-3LIt0EQqzzzUzzQfLEWer0e46ILDNAzY83zpymvx4tc/include -isystem /home/alex/local/tmp/ubuntu-22.04/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/installed/rocksdb-aPC428riMYM8VWb0qNZq4ayYUH88kYvySX0pZMqbSFw/include -g -Wall -Wextra -Wno-deprecated -Wno-deprecated-declarations -Wno-nullability-completeness -Wno-unknown-pragmas -O2 -g -DNDEBUG -fsized-deallocation -MD -MT eden/fs/utils/test/CMakeFiles/eden_utils_test.dir/RingBufferTest.cpp.o -MF eden/fs/utils/test/CMakeFiles/eden_utils_test.dir/RingBufferTest.cpp.o.d -o eden/fs/utils/test/CMakeFiles/eden_utils_test.dir/RingBufferTest.cpp.o -c /home/alex/local/sapling/eden/fs/utils/test/RingBufferTest.cpp
In file included from /home/alex/local/sapling/eden/fs/utils/test/RingBufferTest.cpp:8:
/home/alex/local/sapling/eden/fs/utils/RingBuffer.h:23:29: error: expected ‘)’ before ‘capacity’
   23 |   explicit RingBuffer(size_t capacity);
      |                      ~      ^~~~~~~~~
      |                             )
/home/alex/local/sapling/eden/fs/utils/RingBuffer.h:28:3: error: ‘size_t’ does not name a type
   28 |   size_t capacity() const {
      |   ^~~~~~
/home/alex/local/sapling/eden/fs/utils/RingBuffer.h:11:1: note: ‘size_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
   10 | #include <vector>
  +++ |+#include <cstddef>

```

After, works